import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = dirname(fileURLToPath(import.meta.url));
const indexFile = "index.ts";
const generatedHeader = "// Generated by generate-indexes.mjs. Do not edit manually.\n\n";
const checkOnly = process.argv.includes("--check");
const unknownArguments = process.argv.slice(2).filter((argument) => argument !== "--check");

if (unknownArguments.length > 0) {
  throw new Error(`Unknown argument(s): ${unknownArguments.join(", ")}`);
}

function listModules(directory, predicate = () => true) {
  return readdirSync(directory, { withFileTypes: true })
    .filter(
      (entry) =>
        entry.isFile() &&
        entry.name !== indexFile &&
        entry.name.endsWith(".ts") &&
        !entry.name.endsWith(".d.ts") &&
        predicate(entry.name)
    )
    .map((entry) => entry.name.slice(0, -3))
    .sort();
}

function assertIdentifier(name, sourcePath) {
  if (!/^[$A-Z_a-z][$\w]*$/.test(name)) {
    throw new Error(`Cannot generate an import for ${relative(projectRoot, sourcePath)}: ${name} is not an identifier`);
  }
}

function buildPacketIndex(directory, moduleImportPath) {
  const modules = listModules(directory);

  for (const moduleName of modules) {
    assertIdentifier(moduleName, join(directory, `${moduleName}.ts`));
  }

  const imports = modules.map((moduleName) => `import ${moduleName} from "${moduleImportPath}/${moduleName}";`).join("\n");
  const exports = modules.map((moduleName) => `  ${moduleName},`).join("\n");

  return `${generatedHeader}${imports}\n\nexport {\n${exports}\n};\n`;
}

function buildMutatorIndex(directory, packetDirectory, mutatorImportPath, packetImportPath) {
  const mutators = listModules(directory);
  const packetModules = listModules(packetDirectory);
  const imports = [];
  const registrations = [];

  for (const mutatorName of mutators) {
    assertIdentifier(mutatorName, join(directory, `${mutatorName}.ts`));

    if (!mutatorName.endsWith("Mutator")) {
      throw new Error(`${relative(projectRoot, join(directory, `${mutatorName}.ts`))} must end with Mutator`);
    }

    const packetName = mutatorName.slice(0, -"Mutator".length);
    const matchingPacketModules = packetModules.filter(
      (moduleName) => moduleName === packetName || moduleName.endsWith(`_${packetName}`)
    );

    if (matchingPacketModules.length !== 1) {
      throw new Error(
        `${mutatorName} must have exactly one matching packet in ${relative(projectRoot, packetDirectory)}; found ${matchingPacketModules.length}`
      );
    }

    const packetModule = matchingPacketModules[0];
    imports.push(`import ${mutatorName} from "${mutatorImportPath}/${mutatorName}";`);
    imports.push(`import ${packetModule} from "${packetImportPath}/${packetModule}";`);
    registrations.push(`  [${mutatorName}.prototype, ${packetModule}],`);
  }

  return `${generatedHeader}${imports.join("\n")}\n\nexport default [\n${registrations.join("\n")}\n];\n`;
}

function buildCommandIndex(directory) {
  const commands = listModules(directory, (name) => name.startsWith("Command"));
  const commandKeys = new Set();
  const imports = [];
  const registrations = [];

  for (const commandName of commands) {
    assertIdentifier(commandName, join(directory, `${commandName}.ts`));

    const suffix = commandName.slice("Command".length);
    if (suffix.length === 0) {
      throw new Error(`${commandName}.ts does not define a command name`);
    }

    const commandKey = suffix[0].toLowerCase() + suffix.slice(1);
    if (commandKeys.has(commandKey)) {
      throw new Error(`Duplicate generated command key: ${commandKey}`);
    }

    commandKeys.add(commandKey);
    imports.push(`import ${commandName} from "./${commandName}";`);
    registrations.push(`  ${commandKey}: ${commandName}.prototype,`);
  }

  return `${generatedHeader}${imports.join("\n")}\n\nexport default {\n${registrations.join("\n")}\n};\n`;
}

const incomingGameDirectory = join(projectRoot, "src", "network", "incoming", "game");
const incomingLoginDirectory = join(projectRoot, "src", "network", "incoming", "login");
const mutatorsGameDirectory = join(projectRoot, "src", "network", "mutators", "game");
const mutatorsLoginDirectory = join(projectRoot, "src", "network", "mutators", "login");
const commandsDirectory = join(projectRoot, "src", "commands");

const generatedFiles = new Map([
  [join(incomingGameDirectory, indexFile), buildPacketIndex(incomingGameDirectory, "@network/incoming/game")],
  [join(incomingLoginDirectory, indexFile), buildPacketIndex(incomingLoginDirectory, "@network/incoming/login")],
  [
    join(mutatorsGameDirectory, indexFile),
    buildMutatorIndex(
      mutatorsGameDirectory,
      incomingGameDirectory,
      "@network/mutators/game",
      "@network/incoming/game"
    ),
  ],
  [
    join(mutatorsLoginDirectory, indexFile),
    buildMutatorIndex(
      mutatorsLoginDirectory,
      incomingLoginDirectory,
      "@network/mutators/login",
      "@network/incoming/login"
    ),
  ],
  [join(commandsDirectory, indexFile), buildCommandIndex(commandsDirectory)],
]);

const changedFiles = [];

for (const [filePath, content] of generatedFiles) {
  const currentContent = existsSync(filePath) ? readFileSync(filePath, "utf8") : undefined;

  if (currentContent === content) {
    continue;
  }

  changedFiles.push(relative(projectRoot, filePath));
  if (!checkOnly) {
    writeFileSync(filePath, content, "utf8");
  }
}

if (checkOnly && changedFiles.length > 0) {
  console.error("Generated indexes are stale:");
  for (const filePath of changedFiles) {
    console.error(`  ${filePath}`);
  }
  console.error("Run `npm run generate` and commit the updated files.");
  process.exitCode = 1;
} else if (!checkOnly && changedFiles.length > 0) {
  console.log(`Generated ${changedFiles.length} index file(s).`);
}
