export const enum ClanPrivilege {
    None,
    InviteToClan,
    GrantTitle = 1 << 2,
    WarehouseAccess = 1 << 3,
    ManageRanks = 1 << 4,
    PledgeWar = 1 << 5,
    DismissMember = 1 << 6,
    RegisterCrest = 1 << 7,
    InviteApprentice = 1 << 8,
    NameTroops = 1 << 9,
    SummonAirship = 1 << 10,
    ClanHallOpenDoors = 1 << 11,
    ClanHallMiscellaneous = 1 << 12,
    ClanHallAuction = 1 << 13,
    ClanHallDismiss = 1 << 14,
    ClanHallSetFunctions = 1 << 15,
    CastleOpenDoors = 1 << 16,
    CastleManor = 1 << 17,
    CastleSiege = 1 << 18,
    CastleUseFunctions = 1 << 19,
    CastleDismiss = 1 << 20,
    CastleTaxes = 1 << 21,
    CastleMercenaries = 1 << 22,
    CastleSetFunctions = 1 << 23
}