export enum L2InstanceType {
  L2Object,
  L2ItemInstance,
  L2Character,
  L2Npc,
  L2Playable,
  L2Summon,
  L2Decoy,
  L2PcInstance,
  L2NpcInstance,
  L2MerchantInstance,
  L2WarehouseInstance,
  L2StaticObjectInstance,
  L2DoorInstance,
  L2TerrainObjectInstance,
  L2EffectPointInstance,
  // Summons, Pets, Decoys and Traps
  L2ServitorInstance,
  L2PetInstance,
  L2BabyPetInstance,
  L2DecoyInstance,
  L2TrapInstance,
  // Attackable
  L2Attackable,
  L2GuardInstance,
  L2QuestGuardInstance,
  L2MonsterInstance,
  L2ChestInstance,
  L2ControllableMobInstance,
  L2FeedableBeastInstance,
  L2TamedBeastInstance,
  L2FriendlyMobInstance,
  L2RiftInvaderInstance,
  L2RaidBossInstance,
  L2GrandBossInstance,
  // FlyMobs
  L2FlyNpcInstance,
  L2FlyMonsterInstance,
  L2FlyRaidBossInstance,
  L2FlyTerrainObjectInstance,
  // Sepulchers
  L2SepulcherNpcInstance,
  L2SepulcherMonsterInstance,
  // Festival
  L2FestivalGiudeInstance,
  L2FestivalMonsterInstance,
  // Vehicles
  L2Vehicle,
  L2BoatInstance,
  L2AirShipInstance,
  L2ControllableAirShipInstance,
  // Siege
  L2DefenderInstance,
  L2ArtefactInstance,
  L2ControlTowerInstance,
  L2FlameTowerInstance,
  L2SiegeFlagInstance,
  // Fort Siege
  L2FortCommanderInstance,
  // Fort NPCs
  L2FortLogisticsInstance,
  L2FortManagerInstance,
  // Seven Signs
  L2SignsPriestInstance,
  L2DawnPriestInstance,
  L2DuskPriestInstance,
  L2DungeonGatekeeperInstance,
  // City NPCs
  L2AdventurerInstance,
  L2AuctioneerInstance,
  L2ClanHallManagerInstance,
  L2FishermanInstance,
  L2ObservationInstance,
  L2OlympiadManagerInstance,
  L2PetManagerInstance,
  L2RaceManagerInstance,
  L2TeleporterInstance,
  L2TrainerInstance,
  L2VillageMasterInstance,
  // Doormens
  L2DoormenInstance,
  L2CastleDoormenInstance,
  L2FortDoormenInstance,
  L2ClanHallDoormenInstance,
  // Custom
  L2NpcBufferInstance,
  L2EventMobInstance,
}
