// Generated by generate-indexes.mjs. Do not edit manually.

import CommandAbortQuest from "./CommandAbortQuest";
import CommandAcceptJoinClan from "./CommandAcceptJoinClan";
import CommandAcceptJoinParty from "./CommandAcceptJoinParty";
import CommandAcceptResurrect from "./CommandAcceptResurrect";
import CommandAcceptTrade from "./CommandAcceptTrade";
import CommandAddTradeItem from "./CommandAddTradeItem";
import CommandAttack from "./CommandAttack";
import CommandAutoShots from "./CommandAutoShots";
import CommandCancelBuff from "./CommandCancelBuff";
import CommandCancelTarget from "./CommandCancelTarget";
import CommandCancelTrade from "./CommandCancelTrade";
import CommandCast from "./CommandCast";
import CommandChangePartyLeader from "./CommandChangePartyLeader";
import CommandClanInvite from "./CommandClanInvite";
import CommandCommonCraftRecipes from "./CommandCommonCraftRecipes";
import CommandConfirmTrade from "./CommandConfirmTrade";
import CommandCraft from "./CommandCraft";
import CommandCrystallizeItem from "./CommandCrystallizeItem";
import CommandDeclineJoinClan from "./CommandDeclineJoinClan";
import CommandDeclineJoinParty from "./CommandDeclineJoinParty";
import CommandDeclineResurrect from "./CommandDeclineResurrect";
import CommandDeclineTrade from "./CommandDeclineTrade";
import CommandDeleteRecipe from "./CommandDeleteRecipe";
import CommandDestroyItem from "./CommandDestroyItem";
import CommandDropItem from "./CommandDropItem";
import CommandDwarvenCraftRecipes from "./CommandDwarvenCraftRecipes";
import CommandEnter from "./CommandEnter";
import CommandGiveNickname from "./CommandGiveNickname";
import CommandHit from "./CommandHit";
import CommandInventory from "./CommandInventory";
import CommandItemLink from "./CommandItemLink";
import CommandLeaveClan from "./CommandLeaveClan";
import CommandLeaveParty from "./CommandLeaveParty";
import CommandLogout from "./CommandLogout";
import CommandMoveTo from "./CommandMoveTo";
import CommandNextTarget from "./CommandNextTarget";
import CommandOustPartyMember from "./CommandOustPartyMember";
import CommandQuests from "./CommandQuests";
import CommandRecipeInfo from "./CommandRecipeInfo";
import CommandRequestBypass from "./CommandRequestBypass";
import CommandRequestDuel from "./CommandRequestDuel";
import CommandRequestJoinParty from "./CommandRequestJoinParty";
import CommandRevive from "./CommandRevive";
import CommandRunWalk from "./CommandRunWalk";
import CommandSay from "./CommandSay";
import CommandSayToAlly from "./CommandSayToAlly";
import CommandSayToClan from "./CommandSayToClan";
import CommandSayToParty from "./CommandSayToParty";
import CommandSayToTrade from "./CommandSayToTrade";
import CommandShout from "./CommandShout";
import CommandSitStand from "./CommandSitStand";
import CommandSkills from "./CommandSkills";
import CommandSocialDance from "./CommandSocialDance";
import CommandSocialGreeting from "./CommandSocialGreeting";
import CommandSocialYes from "./CommandSocialYes";
import CommandStopMove from "./CommandStopMove";
import CommandTarget from "./CommandTarget";
import CommandTell from "./CommandTell";
import CommandTradeRequest from "./CommandTradeRequest";
import CommandUnstuck from "./CommandUnstuck";
import CommandUseItem from "./CommandUseItem";
import CommandValidatePosition from "./CommandValidatePosition";

export default {
  abortQuest: CommandAbortQuest.prototype,
  acceptJoinClan: CommandAcceptJoinClan.prototype,
  acceptJoinParty: CommandAcceptJoinParty.prototype,
  acceptResurrect: CommandAcceptResurrect.prototype,
  acceptTrade: CommandAcceptTrade.prototype,
  addTradeItem: CommandAddTradeItem.prototype,
  attack: CommandAttack.prototype,
  autoShots: CommandAutoShots.prototype,
  cancelBuff: CommandCancelBuff.prototype,
  cancelTarget: CommandCancelTarget.prototype,
  cancelTrade: CommandCancelTrade.prototype,
  cast: CommandCast.prototype,
  changePartyLeader: CommandChangePartyLeader.prototype,
  clanInvite: CommandClanInvite.prototype,
  commonCraftRecipes: CommandCommonCraftRecipes.prototype,
  confirmTrade: CommandConfirmTrade.prototype,
  craft: CommandCraft.prototype,
  crystallizeItem: CommandCrystallizeItem.prototype,
  declineJoinClan: CommandDeclineJoinClan.prototype,
  declineJoinParty: CommandDeclineJoinParty.prototype,
  declineResurrect: CommandDeclineResurrect.prototype,
  declineTrade: CommandDeclineTrade.prototype,
  deleteRecipe: CommandDeleteRecipe.prototype,
  destroyItem: CommandDestroyItem.prototype,
  dropItem: CommandDropItem.prototype,
  dwarvenCraftRecipes: CommandDwarvenCraftRecipes.prototype,
  enter: CommandEnter.prototype,
  giveNickname: CommandGiveNickname.prototype,
  hit: CommandHit.prototype,
  inventory: CommandInventory.prototype,
  itemLink: CommandItemLink.prototype,
  leaveClan: CommandLeaveClan.prototype,
  leaveParty: CommandLeaveParty.prototype,
  logout: CommandLogout.prototype,
  moveTo: CommandMoveTo.prototype,
  nextTarget: CommandNextTarget.prototype,
  oustPartyMember: CommandOustPartyMember.prototype,
  quests: CommandQuests.prototype,
  recipeInfo: CommandRecipeInfo.prototype,
  requestBypass: CommandRequestBypass.prototype,
  requestDuel: CommandRequestDuel.prototype,
  requestJoinParty: CommandRequestJoinParty.prototype,
  revive: CommandRevive.prototype,
  runWalk: CommandRunWalk.prototype,
  say: CommandSay.prototype,
  sayToAlly: CommandSayToAlly.prototype,
  sayToClan: CommandSayToClan.prototype,
  sayToParty: CommandSayToParty.prototype,
  sayToTrade: CommandSayToTrade.prototype,
  shout: CommandShout.prototype,
  sitStand: CommandSitStand.prototype,
  skills: CommandSkills.prototype,
  socialDance: CommandSocialDance.prototype,
  socialGreeting: CommandSocialGreeting.prototype,
  socialYes: CommandSocialYes.prototype,
  stopMove: CommandStopMove.prototype,
  target: CommandTarget.prototype,
  tell: CommandTell.prototype,
  tradeRequest: CommandTradeRequest.prototype,
  unstuck: CommandUnstuck.prototype,
  useItem: CommandUseItem.prototype,
  validatePosition: CommandValidatePosition.prototype,
};
