// Generated by generate-indexes.mjs. Do not edit manually.

import AbnormalStatusUpdateMutator from "./AbnormalStatusUpdateMutator";
import x85_AbnormalStatusUpdate from "../../incoming/game/x85_AbnormalStatusUpdate";
import ActionFailedMutator from "./ActionFailedMutator";
import x1F_ActionFailed from "../../incoming/game/x1F_ActionFailed";
import AskJoinPartyMutator from "./AskJoinPartyMutator";
import x39_AskJoinParty from "../../incoming/game/x39_AskJoinParty";
import AttackMutator from "./AttackMutator";
import x33_Attack from "../../incoming/game/x33_Attack";
import ChangeWaitTypeMutator from "./ChangeWaitTypeMutator";
import x29_ChangeWaitType from "../../incoming/game/x29_ChangeWaitType";
import CharInfoMutator from "./CharInfoMutator";
import x31_CharInfo from "../../incoming/game/x31_CharInfo";
import CharSelectedMutator from "./CharSelectedMutator";
import x0B_CharSelected from "../../incoming/game/x0B_CharSelected";
import ConfirmDlgMutator from "./ConfirmDlgMutator";
import xF3_ConfirmDlg from "../../incoming/game/xF3_ConfirmDlg";
import CreatureSayMutator from "./CreatureSayMutator";
import x4A_CreatureSay from "../../incoming/game/x4A_CreatureSay";
import DeleteObjectMutator from "./DeleteObjectMutator";
import x08_DeleteObject from "../../incoming/game/x08_DeleteObject";
import DieMutator from "./DieMutator";
import x00_Die from "../../incoming/game/x00_Die";
import DropItemMutator from "./DropItemMutator";
import x16_DropItem from "../../incoming/game/x16_DropItem";
import EtcStatusUpdateMutator from "./EtcStatusUpdateMutator";
import xF9_EtcStatusUpdate from "../../incoming/game/xF9_EtcStatusUpdate";
import ExDuelAskStartMutator from "./ExDuelAskStartMutator";
import xFE_x4C_ExDuelAskStart from "../../incoming/game/xFE_x4C_ExDuelAskStart";
import ExQuestItemListMutator from "./ExQuestItemListMutator";
import xFE_xC6_ExQuestItemList from "../../incoming/game/xFE_xC6_ExQuestItemList";
import ExRotationMutator from "./ExRotationMutator";
import xFE_xC1_ExRotation from "../../incoming/game/xFE_xC1_ExRotation";
import ExVoteSystemInfoMutator from "./ExVoteSystemInfoMutator";
import xFE_xC9_ExVoteSystemInfo from "../../incoming/game/xFE_xC9_ExVoteSystemInfo";
import InventoryUpdateMutator from "./InventoryUpdateMutator";
import x21_InventoryUpdate from "../../incoming/game/x21_InventoryUpdate";
import ItemListMutator from "./ItemListMutator";
import x11_ItemList from "../../incoming/game/x11_ItemList";
import KeyPacketMutator from "./KeyPacketMutator";
import x2E_KeyPacket from "../../incoming/game/x2E_KeyPacket";
import MagicSkillUseMutator from "./MagicSkillUseMutator";
import x48_MagicSkillUse from "../../incoming/game/x48_MagicSkillUse";
import MoveToLocationMutator from "./MoveToLocationMutator";
import x2F_MoveToLocation from "../../incoming/game/x2F_MoveToLocation";
import MoveToPawnMutator from "./MoveToPawnMutator";
import x72_MoveToPawn from "../../incoming/game/x72_MoveToPawn";
import MyTargetSelectedMutator from "./MyTargetSelectedMutator";
import xB9_MyTargetSelected from "../../incoming/game/xB9_MyTargetSelected";
import NpcHtmlMessageMutator from "./NpcHtmlMessageMutator";
import x19_NpcHtmlMessage from "../../incoming/game/x19_NpcHtmlMessage";
import NpcInfoMutator from "./NpcInfoMutator";
import x0C_NpcInfo from "../../incoming/game/x0C_NpcInfo";
import NpcQuestHtmlMessageMutator from "./NpcQuestHtmlMessageMutator";
import xFE_x8D_NpcQuestHtmlMessage from "../../incoming/game/xFE_x8D_NpcQuestHtmlMessage";
import PartyMemberPositionMutator from "./PartyMemberPositionMutator";
import xBA_PartyMemberPosition from "../../incoming/game/xBA_PartyMemberPosition";
import PartySmallWindowAddMutator from "./PartySmallWindowAddMutator";
import x4F_PartySmallWindowAdd from "../../incoming/game/x4F_PartySmallWindowAdd";
import PartySmallWindowAllMutator from "./PartySmallWindowAllMutator";
import x4E_PartySmallWindowAll from "../../incoming/game/x4E_PartySmallWindowAll";
import PartySmallWindowDeleteAllMutator from "./PartySmallWindowDeleteAllMutator";
import x50_PartySmallWindowDeleteAll from "../../incoming/game/x50_PartySmallWindowDeleteAll";
import PartySmallWindowDeleteMutator from "./PartySmallWindowDeleteMutator";
import x51_PartySmallWindowDelete from "../../incoming/game/x51_PartySmallWindowDelete";
import PartySmallWindowUpdateMutator from "./PartySmallWindowUpdateMutator";
import x52_PartySmallWindowUpdate from "../../incoming/game/x52_PartySmallWindowUpdate";
import PartySpelledMutator from "./PartySpelledMutator";
import xF4_PartySpelled from "../../incoming/game/xF4_PartySpelled";
import RecipeBookItemListMutator from "./RecipeBookItemListMutator";
import xDC_RecipeBookItemList from "../../incoming/game/xDC_RecipeBookItemList";
import RecipeItemMakeInfoMutator from "./RecipeItemMakeInfoMutator";
import xDD_RecipeItemMakeInfo from "../../incoming/game/xDD_RecipeItemMakeInfo";
import ReviveMutator from "./ReviveMutator";
import x01_Revive from "../../incoming/game/x01_Revive";
import SetupGaugeMutator from "./SetupGaugeMutator";
import x6B_SetupGauge from "../../incoming/game/x6B_SetupGauge";
import SkillCoolTimeMutator from "./SkillCoolTimeMutator";
import xC7_SkillCoolTime from "../../incoming/game/xC7_SkillCoolTime";
import SkillListMutator from "./SkillListMutator";
import x5F_SkillList from "../../incoming/game/x5F_SkillList";
import SpawnItemMutator from "./SpawnItemMutator";
import x05_SpawnItem from "../../incoming/game/x05_SpawnItem";
import StatusUpdateMutator from "./StatusUpdateMutator";
import x18_StatusUpdate from "../../incoming/game/x18_StatusUpdate";
import StopMoveMutator from "./StopMoveMutator";
import x47_StopMove from "../../incoming/game/x47_StopMove";
import SystemMessageMutator from "./SystemMessageMutator";
import x62_SystemMessage from "../../incoming/game/x62_SystemMessage";
import TargetSelectedMutator from "./TargetSelectedMutator";
import x23_TargetSelected from "../../incoming/game/x23_TargetSelected";
import TargetUnselectedMutator from "./TargetUnselectedMutator";
import x24_TargetUnselected from "../../incoming/game/x24_TargetUnselected";
import TeleportToLocationMutator from "./TeleportToLocationMutator";
import x22_TeleportToLocation from "../../incoming/game/x22_TeleportToLocation";
import UserInfoMutator from "./UserInfoMutator";
import x32_UserInfo from "../../incoming/game/x32_UserInfo";
import ValidateLocationMutator from "./ValidateLocationMutator";
import x79_ValidateLocation from "../../incoming/game/x79_ValidateLocation";

export default [
  [AbnormalStatusUpdateMutator.prototype, x85_AbnormalStatusUpdate],
  [ActionFailedMutator.prototype, x1F_ActionFailed],
  [AskJoinPartyMutator.prototype, x39_AskJoinParty],
  [AttackMutator.prototype, x33_Attack],
  [ChangeWaitTypeMutator.prototype, x29_ChangeWaitType],
  [CharInfoMutator.prototype, x31_CharInfo],
  [CharSelectedMutator.prototype, x0B_CharSelected],
  [ConfirmDlgMutator.prototype, xF3_ConfirmDlg],
  [CreatureSayMutator.prototype, x4A_CreatureSay],
  [DeleteObjectMutator.prototype, x08_DeleteObject],
  [DieMutator.prototype, x00_Die],
  [DropItemMutator.prototype, x16_DropItem],
  [EtcStatusUpdateMutator.prototype, xF9_EtcStatusUpdate],
  [ExDuelAskStartMutator.prototype, xFE_x4C_ExDuelAskStart],
  [ExQuestItemListMutator.prototype, xFE_xC6_ExQuestItemList],
  [ExRotationMutator.prototype, xFE_xC1_ExRotation],
  [ExVoteSystemInfoMutator.prototype, xFE_xC9_ExVoteSystemInfo],
  [InventoryUpdateMutator.prototype, x21_InventoryUpdate],
  [ItemListMutator.prototype, x11_ItemList],
  [KeyPacketMutator.prototype, x2E_KeyPacket],
  [MagicSkillUseMutator.prototype, x48_MagicSkillUse],
  [MoveToLocationMutator.prototype, x2F_MoveToLocation],
  [MoveToPawnMutator.prototype, x72_MoveToPawn],
  [MyTargetSelectedMutator.prototype, xB9_MyTargetSelected],
  [NpcHtmlMessageMutator.prototype, x19_NpcHtmlMessage],
  [NpcInfoMutator.prototype, x0C_NpcInfo],
  [NpcQuestHtmlMessageMutator.prototype, xFE_x8D_NpcQuestHtmlMessage],
  [PartyMemberPositionMutator.prototype, xBA_PartyMemberPosition],
  [PartySmallWindowAddMutator.prototype, x4F_PartySmallWindowAdd],
  [PartySmallWindowAllMutator.prototype, x4E_PartySmallWindowAll],
  [PartySmallWindowDeleteAllMutator.prototype, x50_PartySmallWindowDeleteAll],
  [PartySmallWindowDeleteMutator.prototype, x51_PartySmallWindowDelete],
  [PartySmallWindowUpdateMutator.prototype, x52_PartySmallWindowUpdate],
  [PartySpelledMutator.prototype, xF4_PartySpelled],
  [RecipeBookItemListMutator.prototype, xDC_RecipeBookItemList],
  [RecipeItemMakeInfoMutator.prototype, xDD_RecipeItemMakeInfo],
  [ReviveMutator.prototype, x01_Revive],
  [SetupGaugeMutator.prototype, x6B_SetupGauge],
  [SkillCoolTimeMutator.prototype, xC7_SkillCoolTime],
  [SkillListMutator.prototype, x5F_SkillList],
  [SpawnItemMutator.prototype, x05_SpawnItem],
  [StatusUpdateMutator.prototype, x18_StatusUpdate],
  [StopMoveMutator.prototype, x47_StopMove],
  [SystemMessageMutator.prototype, x62_SystemMessage],
  [TargetSelectedMutator.prototype, x23_TargetSelected],
  [TargetUnselectedMutator.prototype, x24_TargetUnselected],
  [TeleportToLocationMutator.prototype, x22_TeleportToLocation],
  [UserInfoMutator.prototype, x32_UserInfo],
  [ValidateLocationMutator.prototype, x79_ValidateLocation],
];
