// Generated by generate-indexes.mjs. Do not edit manually.

import AbnormalStatusUpdateMutator from "@network/mutators/game/AbnormalStatusUpdateMutator";
import x85_AbnormalStatusUpdate from "@network/incoming/game/x85_AbnormalStatusUpdate";
import ActionFailedMutator from "@network/mutators/game/ActionFailedMutator";
import x1F_ActionFailed from "@network/incoming/game/x1F_ActionFailed";
import AskJoinPartyMutator from "@network/mutators/game/AskJoinPartyMutator";
import x39_AskJoinParty from "@network/incoming/game/x39_AskJoinParty";
import AttackMutator from "@network/mutators/game/AttackMutator";
import x33_Attack from "@network/incoming/game/x33_Attack";
import ChangeWaitTypeMutator from "@network/mutators/game/ChangeWaitTypeMutator";
import x29_ChangeWaitType from "@network/incoming/game/x29_ChangeWaitType";
import CharInfoMutator from "@network/mutators/game/CharInfoMutator";
import x31_CharInfo from "@network/incoming/game/x31_CharInfo";
import CharSelectedMutator from "@network/mutators/game/CharSelectedMutator";
import x0B_CharSelected from "@network/incoming/game/x0B_CharSelected";
import ConfirmDlgMutator from "@network/mutators/game/ConfirmDlgMutator";
import xF3_ConfirmDlg from "@network/incoming/game/xF3_ConfirmDlg";
import CreatureSayMutator from "@network/mutators/game/CreatureSayMutator";
import x4A_CreatureSay from "@network/incoming/game/x4A_CreatureSay";
import DeleteObjectMutator from "@network/mutators/game/DeleteObjectMutator";
import x08_DeleteObject from "@network/incoming/game/x08_DeleteObject";
import DieMutator from "@network/mutators/game/DieMutator";
import x00_Die from "@network/incoming/game/x00_Die";
import DropItemMutator from "@network/mutators/game/DropItemMutator";
import x16_DropItem from "@network/incoming/game/x16_DropItem";
import EtcStatusUpdateMutator from "@network/mutators/game/EtcStatusUpdateMutator";
import xF9_EtcStatusUpdate from "@network/incoming/game/xF9_EtcStatusUpdate";
import ExDuelAskStartMutator from "@network/mutators/game/ExDuelAskStartMutator";
import xFE_x4C_ExDuelAskStart from "@network/incoming/game/xFE_x4C_ExDuelAskStart";
import ExPrivateStoreSetWholeMsgMutator from "@network/mutators/game/ExPrivateStoreSetWholeMsgMutator";
import xFE_x80_ExPrivateStoreSetWholeMsg from "@network/incoming/game/xFE_x80_ExPrivateStoreSetWholeMsg";
import ExQuestItemListMutator from "@network/mutators/game/ExQuestItemListMutator";
import xFE_xC6_ExQuestItemList from "@network/incoming/game/xFE_xC6_ExQuestItemList";
import ExRotationMutator from "@network/mutators/game/ExRotationMutator";
import xFE_xC1_ExRotation from "@network/incoming/game/xFE_xC1_ExRotation";
import ExVoteSystemInfoMutator from "@network/mutators/game/ExVoteSystemInfoMutator";
import xFE_xC9_ExVoteSystemInfo from "@network/incoming/game/xFE_xC9_ExVoteSystemInfo";
import InventoryUpdateMutator from "@network/mutators/game/InventoryUpdateMutator";
import x21_InventoryUpdate from "@network/incoming/game/x21_InventoryUpdate";
import ItemListMutator from "@network/mutators/game/ItemListMutator";
import x11_ItemList from "@network/incoming/game/x11_ItemList";
import KeyPacketMutator from "@network/mutators/game/KeyPacketMutator";
import x2E_KeyPacket from "@network/incoming/game/x2E_KeyPacket";
import MagicSkillUseMutator from "@network/mutators/game/MagicSkillUseMutator";
import x48_MagicSkillUse from "@network/incoming/game/x48_MagicSkillUse";
import MoveToLocationMutator from "@network/mutators/game/MoveToLocationMutator";
import x2F_MoveToLocation from "@network/incoming/game/x2F_MoveToLocation";
import MoveToPawnMutator from "@network/mutators/game/MoveToPawnMutator";
import x72_MoveToPawn from "@network/incoming/game/x72_MoveToPawn";
import MyTargetSelectedMutator from "@network/mutators/game/MyTargetSelectedMutator";
import xB9_MyTargetSelected from "@network/incoming/game/xB9_MyTargetSelected";
import NpcHtmlMessageMutator from "@network/mutators/game/NpcHtmlMessageMutator";
import x19_NpcHtmlMessage from "@network/incoming/game/x19_NpcHtmlMessage";
import NpcInfoMutator from "@network/mutators/game/NpcInfoMutator";
import x0C_NpcInfo from "@network/incoming/game/x0C_NpcInfo";
import NpcQuestHtmlMessageMutator from "@network/mutators/game/NpcQuestHtmlMessageMutator";
import xFE_x8D_NpcQuestHtmlMessage from "@network/incoming/game/xFE_x8D_NpcQuestHtmlMessage";
import PartyMemberPositionMutator from "@network/mutators/game/PartyMemberPositionMutator";
import xBA_PartyMemberPosition from "@network/incoming/game/xBA_PartyMemberPosition";
import PartySmallWindowAddMutator from "@network/mutators/game/PartySmallWindowAddMutator";
import x4F_PartySmallWindowAdd from "@network/incoming/game/x4F_PartySmallWindowAdd";
import PartySmallWindowAllMutator from "@network/mutators/game/PartySmallWindowAllMutator";
import x4E_PartySmallWindowAll from "@network/incoming/game/x4E_PartySmallWindowAll";
import PartySmallWindowDeleteAllMutator from "@network/mutators/game/PartySmallWindowDeleteAllMutator";
import x50_PartySmallWindowDeleteAll from "@network/incoming/game/x50_PartySmallWindowDeleteAll";
import PartySmallWindowDeleteMutator from "@network/mutators/game/PartySmallWindowDeleteMutator";
import x51_PartySmallWindowDelete from "@network/incoming/game/x51_PartySmallWindowDelete";
import PartySmallWindowUpdateMutator from "@network/mutators/game/PartySmallWindowUpdateMutator";
import x52_PartySmallWindowUpdate from "@network/incoming/game/x52_PartySmallWindowUpdate";
import PartySpelledMutator from "@network/mutators/game/PartySpelledMutator";
import xF4_PartySpelled from "@network/incoming/game/xF4_PartySpelled";
import PledgeInfoMutator from "@network/mutators/game/PledgeInfoMutator";
import x89_PledgeInfo from "@network/incoming/game/x89_PledgeInfo";
import PrivateStoreMsgBuyMutator from "@network/mutators/game/PrivateStoreMsgBuyMutator";
import xBF_PrivateStoreMsgBuy from "@network/incoming/game/xBF_PrivateStoreMsgBuy";
import PrivateStoreMsgSellMutator from "@network/mutators/game/PrivateStoreMsgSellMutator";
import xA2_PrivateStoreMsgSell from "@network/incoming/game/xA2_PrivateStoreMsgSell";
import QuestListMutator from "@network/mutators/game/QuestListMutator";
import x86_QuestList from "@network/incoming/game/x86_QuestList";
import RecipeBookItemListMutator from "@network/mutators/game/RecipeBookItemListMutator";
import xDC_RecipeBookItemList from "@network/incoming/game/xDC_RecipeBookItemList";
import RecipeItemMakeInfoMutator from "@network/mutators/game/RecipeItemMakeInfoMutator";
import xDD_RecipeItemMakeInfo from "@network/incoming/game/xDD_RecipeItemMakeInfo";
import ReviveMutator from "@network/mutators/game/ReviveMutator";
import x01_Revive from "@network/incoming/game/x01_Revive";
import SendMacroListMutator from "@network/mutators/game/SendMacroListMutator";
import xE8_SendMacroList from "@network/incoming/game/xE8_SendMacroList";
import SetupGaugeMutator from "@network/mutators/game/SetupGaugeMutator";
import x6B_SetupGauge from "@network/incoming/game/x6B_SetupGauge";
import SkillCoolTimeMutator from "@network/mutators/game/SkillCoolTimeMutator";
import xC7_SkillCoolTime from "@network/incoming/game/xC7_SkillCoolTime";
import SkillListMutator from "@network/mutators/game/SkillListMutator";
import x5F_SkillList from "@network/incoming/game/x5F_SkillList";
import SpawnItemMutator from "@network/mutators/game/SpawnItemMutator";
import x05_SpawnItem from "@network/incoming/game/x05_SpawnItem";
import StatusUpdateMutator from "@network/mutators/game/StatusUpdateMutator";
import x18_StatusUpdate from "@network/incoming/game/x18_StatusUpdate";
import StopMoveMutator from "@network/mutators/game/StopMoveMutator";
import x47_StopMove from "@network/incoming/game/x47_StopMove";
import SystemMessageMutator from "@network/mutators/game/SystemMessageMutator";
import x62_SystemMessage from "@network/incoming/game/x62_SystemMessage";
import TargetSelectedMutator from "@network/mutators/game/TargetSelectedMutator";
import x23_TargetSelected from "@network/incoming/game/x23_TargetSelected";
import TargetUnselectedMutator from "@network/mutators/game/TargetUnselectedMutator";
import x24_TargetUnselected from "@network/incoming/game/x24_TargetUnselected";
import TeleportToLocationMutator from "@network/mutators/game/TeleportToLocationMutator";
import x22_TeleportToLocation from "@network/incoming/game/x22_TeleportToLocation";
import UserInfoMutator from "@network/mutators/game/UserInfoMutator";
import x32_UserInfo from "@network/incoming/game/x32_UserInfo";
import ValidateLocationMutator from "@network/mutators/game/ValidateLocationMutator";
import x79_ValidateLocation from "@network/incoming/game/x79_ValidateLocation";

export default [
  [AbnormalStatusUpdateMutator.prototype, x85_AbnormalStatusUpdate],
  [ActionFailedMutator.prototype, x1F_ActionFailed],
  [AskJoinPartyMutator.prototype, x39_AskJoinParty],
  [AttackMutator.prototype, x33_Attack],
  [ChangeWaitTypeMutator.prototype, x29_ChangeWaitType],
  [CharInfoMutator.prototype, x31_CharInfo],
  [CharSelectedMutator.prototype, x0B_CharSelected],
  [ConfirmDlgMutator.prototype, xF3_ConfirmDlg],
  [CreatureSayMutator.prototype, x4A_CreatureSay],
  [DeleteObjectMutator.prototype, x08_DeleteObject],
  [DieMutator.prototype, x00_Die],
  [DropItemMutator.prototype, x16_DropItem],
  [EtcStatusUpdateMutator.prototype, xF9_EtcStatusUpdate],
  [ExDuelAskStartMutator.prototype, xFE_x4C_ExDuelAskStart],
  [ExPrivateStoreSetWholeMsgMutator.prototype, xFE_x80_ExPrivateStoreSetWholeMsg],
  [ExQuestItemListMutator.prototype, xFE_xC6_ExQuestItemList],
  [ExRotationMutator.prototype, xFE_xC1_ExRotation],
  [ExVoteSystemInfoMutator.prototype, xFE_xC9_ExVoteSystemInfo],
  [InventoryUpdateMutator.prototype, x21_InventoryUpdate],
  [ItemListMutator.prototype, x11_ItemList],
  [KeyPacketMutator.prototype, x2E_KeyPacket],
  [MagicSkillUseMutator.prototype, x48_MagicSkillUse],
  [MoveToLocationMutator.prototype, x2F_MoveToLocation],
  [MoveToPawnMutator.prototype, x72_MoveToPawn],
  [MyTargetSelectedMutator.prototype, xB9_MyTargetSelected],
  [NpcHtmlMessageMutator.prototype, x19_NpcHtmlMessage],
  [NpcInfoMutator.prototype, x0C_NpcInfo],
  [NpcQuestHtmlMessageMutator.prototype, xFE_x8D_NpcQuestHtmlMessage],
  [PartyMemberPositionMutator.prototype, xBA_PartyMemberPosition],
  [PartySmallWindowAddMutator.prototype, x4F_PartySmallWindowAdd],
  [PartySmallWindowAllMutator.prototype, x4E_PartySmallWindowAll],
  [PartySmallWindowDeleteAllMutator.prototype, x50_PartySmallWindowDeleteAll],
  [PartySmallWindowDeleteMutator.prototype, x51_PartySmallWindowDelete],
  [PartySmallWindowUpdateMutator.prototype, x52_PartySmallWindowUpdate],
  [PartySpelledMutator.prototype, xF4_PartySpelled],
  [PledgeInfoMutator.prototype, x89_PledgeInfo],
  [PrivateStoreMsgBuyMutator.prototype, xBF_PrivateStoreMsgBuy],
  [PrivateStoreMsgSellMutator.prototype, xA2_PrivateStoreMsgSell],
  [QuestListMutator.prototype, x86_QuestList],
  [RecipeBookItemListMutator.prototype, xDC_RecipeBookItemList],
  [RecipeItemMakeInfoMutator.prototype, xDD_RecipeItemMakeInfo],
  [ReviveMutator.prototype, x01_Revive],
  [SendMacroListMutator.prototype, xE8_SendMacroList],
  [SetupGaugeMutator.prototype, x6B_SetupGauge],
  [SkillCoolTimeMutator.prototype, xC7_SkillCoolTime],
  [SkillListMutator.prototype, x5F_SkillList],
  [SpawnItemMutator.prototype, x05_SpawnItem],
  [StatusUpdateMutator.prototype, x18_StatusUpdate],
  [StopMoveMutator.prototype, x47_StopMove],
  [SystemMessageMutator.prototype, x62_SystemMessage],
  [TargetSelectedMutator.prototype, x23_TargetSelected],
  [TargetUnselectedMutator.prototype, x24_TargetUnselected],
  [TeleportToLocationMutator.prototype, x22_TeleportToLocation],
  [UserInfoMutator.prototype, x32_UserInfo],
  [ValidateLocationMutator.prototype, x79_ValidateLocation],
];
