// Generated by generate-indexes.mjs. Do not edit manually.

import InitMutator from "./InitMutator";
import x00_Init from "../../incoming/login/x00_Init";
import LoginOkMutator from "./LoginOkMutator";
import x03_LoginOk from "../../incoming/login/x03_LoginOk";
import PlayOkMutator from "./PlayOkMutator";
import x07_PlayOk from "../../incoming/login/x07_PlayOk";
import ServerListMutator from "./ServerListMutator";
import x04_ServerList from "../../incoming/login/x04_ServerList";

export default [
  [InitMutator.prototype, x00_Init],
  [LoginOkMutator.prototype, x03_LoginOk],
  [PlayOkMutator.prototype, x07_PlayOk],
  [ServerListMutator.prototype, x04_ServerList],
];
