// Generated by generate-indexes.mjs. Do not edit manually.

import InitMutator from "@network/mutators/login/InitMutator";
import x00_Init from "@network/incoming/login/x00_Init";
import LoginOkMutator from "@network/mutators/login/LoginOkMutator";
import x03_LoginOk from "@network/incoming/login/x03_LoginOk";
import PlayOkMutator from "@network/mutators/login/PlayOkMutator";
import x07_PlayOk from "@network/incoming/login/x07_PlayOk";
import ServerListMutator from "@network/mutators/login/ServerListMutator";
import x04_ServerList from "@network/incoming/login/x04_ServerList";

export default [
  [InitMutator.prototype, x00_Init],
  [LoginOkMutator.prototype, x03_LoginOk],
  [PlayOkMutator.prototype, x07_PlayOk],
  [ServerListMutator.prototype, x04_ServerList],
];
